iris
class(iris)
View(iris)
nrow(iris)
ncol(iris)
colnames(iris)
summary(iris)
iris[c("Sepal.Length","Species")]
iris[c(100,103,105),]
iris[50:100,]
mean(iris$Sepal.Length)
median(iris$Sepal.Width)
sd(iris$Petal.Length)
quantile(iris$Petal.Width,probs=seq(0,1,0.1))
min(iris$Petal.Width)
max(iris$Petal.Width)
dfManga<-read.csv("L:/BUT/SD/Promo 2023/cbouteaud/Prog stat/manga.csv",header=TRUE,sep=",",dec=".")
dfAnime<-read.csv("L:/BUT/SD/Promo 2023/cbouteaud/Prog stat/anime.csv",header=TRUE,sep=",",dec=".")
class(dfManga)
class(dfAnime)
View(dfAnime)
View(dfManga)
dim(dfManga)
dim(dfAnime)
a=mean(dfAnime$Score)
b=mean(dfManga$Score)
print(max(a,b))
c=sum(dfAnime$Vote)
d=sum(dfManga$Vote)
print(max(c,d))
e=sd(dfAnime$Score)
f=sd(dfManga$Score)
print(min(e,f))
a=round(quantile(dfAnime$Score,seq(0,1,0.1)),2)
b=round(quantile(dfManga$Score,seq(0,1,0.1)),2)
print(min(a[2],b[2]))
g=subset(dfManga,Score>9)      
nrow(g)
h=subset(dfManga,Vote>200000)
nrow(h)
i=subset(dfManga,Vote>200000&Score>9)
nrow(i)
j=subset(dfManga,Score<9&Score>8)
nrow(j)
k=table(dfAnime$Rating)
print(k)
length(k)
prop.table(k)
l=subset(dfAnime,Rating=="R - 17+ (violence & profanity)")
nrow(l)
m=subset(dfAnime,Rating=="R - 17+ (violence & profanity)"&Score>8)
nrow(m)
n=subset(dfAnime,Rating!="R - 17+ (violence & profanity)")
nrow(n)
o=subset(dfAnime,Rating %in% c("PG - Children ","G - All Ages"))
nrow(o)
p=subset(dfAnime,!Rating %in% c("PG - Children ","G - All Ages"))
nrow(p)
q=subset(dfAnime,Score>9|Vote>400000)
nrow(q)
dfAnime=dfAnime[ ,c("Title","Score","Vote","Ranked")]
dfManga=dfManga[ ,c("Title","Score","Vote","Ranked")]
View(dfAnime)
dfAnime$Type="Anime"
dfManga$Type="Manga"
dfConcat=rbind(dfManga,dfAnime)
View(dfConcat)
write.table(dfConcat,"L:/BUT/SD/Promo 2023/cbouteaud/Prog stat/ExportTp1.csv",sep=";",row.names=FALSE)
